### ISSUE TITLE
Please create a release!

### ISSUE THREAD

**Issue by mdomke** [vmalloc/mongomock#137]
The last release (2.0.0) was about 10 month ago. Since then a lot of commits have been added that contain important bugfixes and improvements. It would be great if you could create a release anytime soon.

**Comment by vmalloc** [comment]
Ok!

**Comment by vmalloc** [comment]
Pushed 2.1.0.

**Comment by mdomke** [comment]
Thanks! Never expected this to happen so fast! ;-)

**Comment by vmalloc** [comment]
No problem. Glad to be of service :-)
