### ISSUE TITLE
Atomic doc update?

### ISSUE THREAD

**Issue by mlowery** [vmalloc/mongomock#138]
Should the following be expected to work? I can get it to throw an `AssertionError` sometimes. It prints:

```bash
{'_id': '1'}
```

```python
import mongomock
import threading

ID1 = '1'

doc = {'_id': ID1, 'extra': 'whatever'}

conn = mongomock.Connection()


def save():
    conn.db1.coll1.save(doc)


def find_one():
    doc = conn.db1.coll1.find_one({'_id': ID1})
    try:
        assert 'extra' in doc
    except AssertionError:
        print doc

# call once to ensure no thread sees it as absent
save()

for i in range(0, 10000):
    threading.Thread(target=save).start()
    threading.Thread(target=find_one).start()
```

Looking at the [code](https://github.com/vmalloc/mongomock/blob/236b45bbec55b0846d85a576df050f0449bfd478/mongomock/collection.py#L253-L256), it does `existing_document.clear()` then copies in the fields. No lock is held during those operations.

Again, I'm primarily interested in if this _should_ work then secondarily interested in a solution.

Great project!

**Comment by vmalloc** [comment]
Nope. Mongomock at its current state is not thread-safe. Sorry to bring bad news :-(

**Comment by mlowery** [comment]
Thanks for the quick response!

**Comment by vmalloc** [comment]
N/p! Pull requests are always welcome BTW if you want to get involved.
