### ISSUE TITLE
Add support for pymongo 3

### ISSUE THREAD

**Issue by mdomke** [vmalloc/mongomock#140]
`pymongo` version 3 includes a couple of API changes, which should be reflected by `mongomock` so that people can profit from the most recent `pymongo` version without loosing the ability to properly unit-test their code. See the `pymongo` [changelog](http://api.mongodb.org/python/current/changelog.html) for detailed information on new and deprecated methods, but most noticeably the new methods are:

* insert_one()
* insert_many()
* update_one()
* update_many()
* replace_one()
* delete_one()
* delete_many()
* find_one_and_delete()
* find_one_and_replace()
* find_one_and_update()

and the deprecated are:

* save()
* insert()
* update()
* remove()
* find_and_modify()

**Comment by xied75** [comment]
:+1: 

second this, would like to know if there will be a target release time

**Comment by vmalloc** [comment]
@xied75  I currently have no actual time to work on mongomock... Pull requests are more than welcome...

**Comment by g----** [comment]
This is vital. Please focus on this. Please, please:)

..or could you recommend any other solution for running tests on pymongo3?

**Comment by mdomke** [comment]
I issued a pull-request #166 that tackles this issue.

**Comment by g----** [comment]
Thank you @mdomke ! 
@vmalloc can you make release with that? Latest installable version with pip is still 2.3.1

Thank you guys very much:)

**Comment by mdomke** [comment]
As I pointed out in my original post this probably should be a braking release (e.g. 3.0), since some things have been removed and/or renamed.

**Comment by vmalloc** [comment]
@g---- sure, will be releasing a new major version soon. Can this be considered fixed? Did you get a chance to test against master?

**Comment by stpierre** [comment]
I've done some fairly small-scale tests and it seems to work. No guarantees
about coverage.

**Comment by vmalloc** [comment]
I will release 3.0.0, hoping not too much would break.
