### ISSUE TITLE
Little Dump/Load feature

### ISSUE THREAD

**Issue by jacobmenick** [vmalloc/mongomock#144]
I added a really simple dump/load feature in my fork.  It just pickles a collection's ```_documents``` attribute. How true to form is the mock db supposed to be? I.e. since no such feature is supported in pymongo, does that mean you don't want to support it here?

**Comment by vmalloc** [comment]
Yes, in general even if it works it's not officially supported as of yet. It could be added, but that requires a bit of thought about how it would be intended to be used.
