### ISSUE TITLE
Testing Multithreaded Code

### ISSUE THREAD

**Issue by jacobmenick** [vmalloc/mongomock#145]
How should one test multithreaded code with a mongomock database? Say I have a thread-safe function for a single document:
```
def doc_func(doc, mock_coll):
       mock_coll.update({'_id': doc['_id'], {'$set': {'field_b': doc['field_a'] +1}}})
```
I wish to go at the whole collection with a work queue or something. How should I share the mongomock database object between multiprocessing processes? I've messed around with proxies and custom managers, but no luck yet.

**Comment by vmalloc** [comment]
one possibility would be to add locks to all mongomock APIs - I don't think there would be anything more sophisticated than that....

**Comment by jacobmenick** [comment]
Would that do it? I am under the impression that due to the GIL, other processes can't touch variables from other processes without some sort of proxy.

**Comment by vmalloc** [comment]
First these are threads, not processes - and secondly I'm not sure what you mean. The GIL only protects the internal interpreter state, so locks are only required when threads touch or modify shared data structures....

**Comment by jacobmenick** [comment]
Oh I see - I said multithreading in the issue title. I should have said "testing parallel code". I'm using the multiprocessing library to take advantage of multiple cores when mapping an operation over a collection (e.g. the function I gave in the issue description.) I'd like to get true parallelism, and hence use "multiprocessing" rather than multithreading. This entails sharing the mock database across processes. Is there a better way to do what I'm after?

**Comment by vmalloc** [comment]
No. Multiprocessing is definitely not compatible with mongomock.

**Comment by jacobmenick** [comment]
Ok. So (I realize this discussion now departs from pertinence to your library) is it the case that I should not bother with the kind of test I'm describing? Or is using multiprocessing a bad idea with this kind of database operation in general? Can you advise on a better way to achieve the parallelism I describe?

**Comment by vmalloc** [comment]
I'm not saying not to test it, just that mongomock is not enough to support it. I would use an actual mongodb process running locally for testing. Assuming you don't want to use the system default, you can have one started as a part of the test setup.

**Comment by jacobmenick** [comment]
Ok. Thank you for your help, Rotem.

**Comment by vmalloc** [comment]
No problem. Good luck.
