### ISSUE TITLE
mongomock has no attribute 'Connection'

### ISSUE THREAD

**Issue by fonglh** [vmalloc/mongomock#184]
The sample code in the README to create a collection seems to have stopped working.

```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mongomock
>>> collection = mongomock.Connection().db.collection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Connection'
>>> 
```

**Comment by mdomke** [comment]
Yes. That is because the mongomock version 3.x only supports pymongo 3.x which has backwards incompatible changes (e.g.: the `Connection` class has been removed). I'll adapt the README accordingly.

**Comment by fonglh** [comment]
Thanks! I got my tests to pass again :+1:
