### ISSUE TITLE
Can not remove from collection while iterating (in python3)

### ISSUE THREAD

**Issue by skonieczny** [vmalloc/mongomock#194]
Following code passes on python2, but fails on python3:

    import mongomock
    
    client = mongomock.MongoClient()
    db = client['db']
    col = db.col
    col.insert({'a': 1})
    col.insert({'b': 2})
    for doc in col.find({}):
        col.remove(doc)

Produces "RuntimeError: OrderedDict mutated during iteration"

**Comment by mdomke** [comment]
The pull request was accidentally merged into master, whereas it should have gone into develop.

**Comment by skonieczny** [comment]
I have created new pull request to the develop branch.
