### ISSUE TITLE
mongomock 3.1.0 files published to pypi have strange extensions and will not download via pip

### ISSUE THREAD

**Issue by declanshanaghy** [vmalloc/mongomock#226]
Are the "py3-none-any.whl" file extensions intentional?

https://pypi.python.org/simple/mongomock/

**Comment by mdomke** [comment]
This is the usual filename nomenclature for wheels https://www.python.org/dev/peps/pep-0427/#file-name-convention.

**Comment by declanshanaghy** [comment]
The env I was trying to install 3.1.0 on was using pip 1.2.1.
Upgrading to pip 1.5.4 solved the issue.

Thx.

**Comment by mdomke** [comment]
Older pip versions do not support wheels. You're probably aware that the
current version of pip is 8.1.2, right?
declanshanaghy <notifications@github.com> schrieb am Mi., 25. Mai 2016 um
18:33:
