### ISSUE TITLE
mongomock is not threadsafe

### ISSUE THREAD

**Issue by thedrow** [vmalloc/mongomock#229]
MongoMock uses OrderedDict instances to store it's collection data.
[OrderedDict is not threadsafe for concurrent writes](http://bugs.python.org/msg134089) but is fine for concurrent reads.
We need to acquire a lock whenever we write to a collection and block reads to that collection until the write is finished,
We should also document the current behaviour.

**Comment by mdomke** [comment]
Feel free to issue a pull request ;-)

**Comment by srinivasreddy** [comment]
Thanks. I will be taking it.

**Comment by srinivasreddy** [comment]
@thedrow   done.

**Comment by thedrow** [comment]
Great! Thank you very much.
