### ISSUE TITLE
six.text_type doesn't include Python 2 string

### ISSUE THREAD

**Issue by JulieRossi** [vmalloc/mongomock#239]
Hi,

You recently (8 days ago commit) replaced isinstance(v, str) or isinstance(v, unicode) by six.text_type in collection.py

Why did you choose six.text_type over six.string_types ?

It seems to me that six.string_types would be more appropriate since six.text_type doesn't support regular Python 2 string.

Indeed, from six documentation (https://pythonhosted.org/six/#six.string_types) :

six.string_types

    Possible types for text data. This is basestring() in Python 2 and str in Python 3.

six.text_type

    Type for representing (Unicode) textual data. This is unicode() in Python 2 and str in Python 3.

**Comment by srinivasreddy** [comment]
I made a mistake. I reverted the change. https://github.com/vmalloc/mongomock/pull/240

Thanks.

**Comment by JulieRossi** [comment]
Thanks !
